:: my_tests.bat
@echo When you continue you will see the first test run ...
@pause
python converter.py
@echo When you continue you will see the second test run ...
@pause
python converter.py time 9572
@echo When you continue you will see the third test run ...
@pause
python converter.py ftemp 89.998
@echo When you continue you will see the fourth test run ...
@pause
python converter.py ctemp 12.01
@echo When you continue you will see the fifth test run ...
@pause
python converter.py timer 72
@echo When you continue this batch file of test runs will terminate ...
@pause
