:: my_tests.bat
@echo When you continue you will see the first test run ...
@pause
python solve_quadratics.py
@echo When you continue you will see the second test run ...
@pause
python solve_quadratics.py 1 3 6
@echo When you continue you will see the third test run ...
@pause
python solve_quadratics.py -2 8 5
@echo When you continue you will see the fourth test run ...
@pause
python solve_quadratics.py 2 3 87 -2
@echo When you continue you will see the fifth test run ... 
@pause
python solve_quadratics.py 1 2
@echo When you continue you will see the sixth test run ... 
@pause
python solve_quadratics.py -4 12 -9
@echo When you continue this batch file of test runs will terminate ...
@pause